apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ems-mvp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ems-mvp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ems-mvp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ems-mvp.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: ems-mvp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
{{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
{{- end }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}