apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::746443183845:role/eksctl-ems-mvp-cluster-addon-iamserviceaccoun-Role1-6cEglEqOATKs
  creationTimestamp: "2026-03-13T21:28:08Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: ems-mvp-sa
  namespace: default
  resourceVersion: "14592"
  uid: be4b3a7e-97c6-44d7-928b-1ad69fdbd14e
