replicaCount: 2

image:
  repository: 746443183845.dkr.ecr.us-east-1.amazonaws.com/ems-mvp-prod
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

env:
  - name: AWS_REGION
    value: "us-east-1"
  - name: BEDROCK_KB_ID
    value: "BJWEDBPNJH"

serviceAccount:
  create: false
  name: ems-mvp-sa
  annotations: {}
serviceAccount:
  create: false
  name: ems-mvp-sa
  annotations: {}
